version: '3.3'

services:
  db:
    image: postgres:12
    volumes:
      - ledger-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    env_file:
      local.env

  admin:
    image: dpage/pgadmin4:latest
    networks:
      - backend
    ports:
      - "9999:80"
    env_file:
      local.env

networks:
  backend:

volumes:
  ledger-data: