version: '3.3'

services:
  db:
    image: postgres:12
    volumes:
      - ledger-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ledgerdb
      POSTGRES_DB: ledger
      POSTGRES_PASSWORD: ledgerdbpass

  admin:
    image: dpage/pgadmin4:latest
    networks:
      - backend
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mattmccants@gmail.com
      PGADMIN_DEFAULT_PASSWORD: donotsharethis

networks:
  backend:

volumes:
  ledger-data: