"""Updates

Revision ID: edd7607cffd1
Revises: fe67361fa473
Create Date: 2020-03-02 17:49:33.259605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'edd7607cffd1'
down_revision = 'fe67361fa473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['id'])
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.create_unique_constraint(None, 'vendors', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'category_id')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
